version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=localhost
      - DB_NAME=mydatabase

  mysql:
    image: mysql:8.0 # Specify the MySQL version (e.g., 8.0)
    container_name: mysql
    network_mode: bridge
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase # Optional: create a default database
      - MYSQL_USER=myuser # Add a new user
      - MYSQL_PASSWORD=mypassword # Set password for the new user
volumes:
  mysql_data:
    name: mysql_data
    driver: local
