version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=mysql
      - DB_NAME=mydatabase
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword

volumes:
  mysql_data:
    name: mysql_data
    driver: local
